"use client";
import Head from "next/head";
import Image from "next/image";
import Weather from "../components/Weather";
import axios from "axios";
import { useState } from "react";
import { BsSearch } from "react-icons/bs";

export default function Home() {
  const [city, setCity] = useState('');
  const [weather, setWeather] = useState({});
  const [loading, setLoading] = useState(false);
  

  const url = `https://api.openweathermap.org/data/2.5/weather?q=${city}&units=imperial&appid=e9f8c74ed9f2949ea5518603b045099c`;

  const fetchWeather = (e) => {
    e.preventDefault();
    setLoading(true);
    axios.get(url).then((response) => {
      setWeather(response.data);
  
    });
    setCity('');
    setLoading(false);
  };

  if (loading) {
    return null;
  } else {
    return (
      <div>
        <Head>
          <title>Weather_App</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
        
        <div className='absolute top-0 left-0 right-0 bottom-0 bg-black/40 z-[1]' />
        <Image src="/background.jpg" alt="/" fill className="object-cover"/>
        <div className='relative flex justify-between items-center max-w-[500px] w-full m-auto pt-4 px-4 text-white z-10'>
          <form
            onSubmit={fetchWeather}
            className='flex justify-between items-center w-full m-auto p-3 bg-transparent border border-gray-300 text-white rounded-2xl'
          >
            <div>
              <input
                onChange={(e) => setCity(e.target.value)}
                className='bg-transparent border-none text-white focus:outline-none text-2xl'
                type='text'
                placeholder='Search city'
              />
            </div>
            <button onClick={fetchWeather}>
              <BsSearch size={20} />
            </button>
          </form>
        </div>

   
        {weather.main && <Weather data={weather} />}
      </div>
    );
  }
}